### ISSUE TITLE
Search response

### ISSUE THREAD

**Issue by ineedhlep** [JessWalters/VinnyBot#27]
## Overview
TODO: Give a brief overview of the issue
Well when I do ~search all the search options pull up but I dont know how to select the one I want.
## Affected commands
TODO: What commands are affected by this issue?
~search
## Expected output
TODO: What was the output of that you were expecting?
For it to play
## Actual output
TODO: What actually happened?
Nothing
## Steps to reproduce
TODO: How can I make this happen again? If you have no idea, what were you doing at the time?
I was trying things like typing in the number ~(number) ~play(number)

**Comment by JessWalters** [comment]
Solved on discord. No Permissions in the channel. Fixed by giving Vinny permissions.
