### ISSUE TITLE
Reddit text posts copies text instead of linking text posts

### ISSUE THREAD

**Issue by mrb25** [JessWalters/VinnyBot#30]
## Overview
For subreddits such as /r/copypasta where the submissions are all text, have an option to just have Vinny copy the text post and post that.

## Affected commands
~tr,~rr copypasta

## Expected output
To be fair, you have to have a very high IQ to understand Rick and Morty. The humour is extremely subtle, and without a solid grasp of theoretical physics most of the jokes will go over a typical viewers head. There's also Rick's nihilistic outlook, which is deftly woven into his characterisation- his personal philosophy draws heavily from Narodnaya Volya literature, for instance. The fans understand this stuff; they have the intellectual capacity to truly appreciate the depths of these jokes, to realise that they're not just funny- they say something deep about LIFE. As a consequence people who dislike Rick & Morty truly ARE idiots- of course they wouldn't appreciate, for instance, the humour in Rick's existential catchphrase "Wubba Lubba Dub Dub," which itself is a cryptic reference to Turgenevs Russian epic Fathers and Sons. I'm smirking right now just imagining one of those addlepated simpletons scratching their heads in confusion as Dan Harmon's genius wit unfolds itself on their television screens. What fools.. how I pity them. 😂

And yes, by the way, i DO have a Rick & Morty tattoo. And no, you cannot see it. It's for the ladies' eyes only- and even then they have to demonstrate that they're within 5 IQ points of my own (preferably lower) beforehand. Nothin personnel kid 😎

## Actual output
https://www.reddit.com/r/copypasta/comments/6qhaln/only_high_iqs_watch_rick_and_morty/

## Steps to reproduce
enter that command boi

**Comment by JessWalters** [comment]
To be fair I don't know if I have an IQ high enough to enjoy Rick and Morty sauce fully. Therefore I will try my best to fulfill this request.

**Comment by JessWalters** [comment]
Closed thanks to @mrb25 in PR #31
