### ISSUE TITLE
Bug in ascii command

### ISSUE THREAD

**Issue by JessWalters** [JessWalters/VinnyBot#33]
## Overview
ascii command with no arguments gives "``````" also when called with @ mentions it looks aweful. Maybe we could just disable it when there is a mention.

## Affected commands
ascii

## Expected output
Preferably error messages

## Actual output
"``````" for no output and a ton of garbage for mentions. 
![image](https://user-images.githubusercontent.com/10608318/32988486-7433bbb6-cccb-11e7-98f8-39c08877e89a.png)

## Steps to reproduce
use command with a mention, or use a command with no args

**Comment by JessWalters** [comment]
@mrb25 
Want to take care of this?

**Comment by mrb25** [comment]
@JessWalters already in the works on my fork. Just doing a lot more bugtesting before making the merge.

**Comment by JessWalters** [comment]
Ok sounds good

**Comment by mrb25** [comment]
Fixed by merge #35
